server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

info:
  app:
    name: java-service
    description: Java demo microservice
    version: 1.0.0
